from binaryninja.log import log_info
log_info("You have now LoongArch64")
from binaryninja.function import RegisterInfo, InstructionInfo, InstructionTextToken, IntrinsicInfo
from binaryninja.architecture import Architecture
from binaryninja.types import Type
from binaryninja.enums import InstructionTextTokenType, BranchType, FlagRole, LowLevelILFlagCondition

class LoongArch64(Architecture):
    name = 'LoongArch64'
    address_size = 8
    max_instr_length = 4

    regs = {
         '$zero' : RegisterInfo('$zero', 8, 0),
         '$ra' : RegisterInfo('$ra', 8, 0),
         '$tp' : RegisterInfo('$tp', 8, 0),
         '$sp' : RegisterInfo('$sp', 8, 0),
         '$a0' : RegisterInfo('$a0', 8, 0),
         '$a1' : RegisterInfo('$a1', 8, 0),
         '$a2' : RegisterInfo('$a2', 8, 0),
         '$a3' : RegisterInfo('$a3', 8, 0),
         '$a4' : RegisterInfo('$a4', 8, 0),
         '$a5' : RegisterInfo('$a5', 8, 0),
         '$a6' : RegisterInfo('$a6', 8, 0),
         '$a7' : RegisterInfo('$a7', 8, 0),
         '$t0' : RegisterInfo('$t0', 8, 0),
         '$t1' : RegisterInfo('$t1', 8, 0),
         '$t2' : RegisterInfo('$t2', 8, 0),
         '$t3' : RegisterInfo('$t3', 8, 0),
         '$t4' : RegisterInfo('$t4', 8, 0),
         '$t5' : RegisterInfo('$t5', 8, 0),
         '$t6' : RegisterInfo('$t6', 8, 0),
         '$t7' : RegisterInfo('$t7', 8, 0),
         '$t8' : RegisterInfo('$t8', 8, 0),
         '$r21' : RegisterInfo('$r21', 8, 0),
         '$fp' : RegisterInfo('$fp',8 , 0),
         '$s0' : RegisterInfo('$s0',8 , 0),
         '$s1' : RegisterInfo('$s1',8 , 0),
         '$s2' : RegisterInfo('$s2',8 , 0),
         '$s3' : RegisterInfo('$s3',8 , 0),
         '$s4' : RegisterInfo('$s4',8 , 0),
         '$s5' : RegisterInfo('$s5',8 , 0),
         '$s6' : RegisterInfo('$s6',8 , 0),
         '$s7' : RegisterInfo('$s7',8 , 0),
         '$s8' : RegisterInfo('$s8',8 , 0),
         '$xr0' : RegisterInfo('$xr0',32 , 0),
         '$xr1' : RegisterInfo('$xr1',32 , 0),
         '$xr2' : RegisterInfo('$xr2',32 , 0),
         '$xr3' : RegisterInfo('$xr3',32 , 0),
         '$xr4' : RegisterInfo('$xr4',32 , 0),
         '$xr5' : RegisterInfo('$xr5',32 , 0),
         '$xr6' : RegisterInfo('$xr6',32 , 0),
         '$xr7' : RegisterInfo('$xr7',32 , 0),
         '$xr8' : RegisterInfo('$xr8',32 , 0),
         '$xr9' : RegisterInfo('$xr9',32 , 0),
         '$xr10' : RegisterInfo('$xr10',32 , 0),
         '$xr11' : RegisterInfo('$xr11',32 , 0),
         '$xr12' : RegisterInfo('$xr12',32 , 0),
         '$xr13' : RegisterInfo('$xr13',32 , 0),
         '$xr14' : RegisterInfo('$xr14',32 , 0),
         '$xr15' : RegisterInfo('$xr15',32 , 0),
         '$xr16' : RegisterInfo('$xr16',32 , 0),
         '$xr17' : RegisterInfo('$xr17',32 , 0),
         '$xr18' : RegisterInfo('$xr18',32 , 0),
         '$xr19' : RegisterInfo('$xr19',32 , 0),
         '$xr20' : RegisterInfo('$xr20',32 , 0),
         '$xr21' : RegisterInfo('$xr21',32 , 0),
         '$xr22' : RegisterInfo('$xr22',32 , 0),
         '$xr23' : RegisterInfo('$xr23',32 , 0),
         '$xr24' : RegisterInfo('$xr24',32 , 0),
         '$xr25' : RegisterInfo('$xr25',32 , 0),
         '$xr26' : RegisterInfo('$xr26',32 , 0),
         '$xr27' : RegisterInfo('$xr27',32 , 0),
         '$xr28' : RegisterInfo('$xr28',32 , 0),
         '$xr29' : RegisterInfo('$xr29',32 , 0),
         '$xr30' : RegisterInfo('$xr30',32 , 0),
         '$xr31' : RegisterInfo('$xr31',32 , 0),
         '$vr0' : RegisterInfo('$xr0', 16, 0),
         '$vr1' : RegisterInfo('$xr1', 16, 0),
         '$vr2' : RegisterInfo('$xr2', 16, 0),
         '$vr3' : RegisterInfo('$xr3', 16, 0),
         '$vr4' : RegisterInfo('$xr4', 16, 0),
         '$vr5' : RegisterInfo('$xr5', 16, 0),
         '$vr6' : RegisterInfo('$xr6', 16, 0),
         '$vr7' : RegisterInfo('$xr7', 16, 0),
         '$vr8' : RegisterInfo('$xr8', 16, 0),
         '$vr9' : RegisterInfo('$xr9', 16, 0),
         '$vr10' : RegisterInfo('$xr10', 16, 0),
         '$vr11' : RegisterInfo('$xr11', 16, 0),
         '$vr12' : RegisterInfo('$xr12', 16, 0),
         '$vr13' : RegisterInfo('$xr13', 16, 0),
         '$vr14' : RegisterInfo('$xr14', 16, 0),
         '$vr15' : RegisterInfo('$xr15', 16, 0),
         '$vr16' : RegisterInfo('$xr16', 16, 0),
         '$vr17' : RegisterInfo('$xr17', 16, 0),
         '$vr18' : RegisterInfo('$xr18', 16, 0),
         '$vr19' : RegisterInfo('$xr19', 16, 0),
         '$vr20' : RegisterInfo('$xr20', 16, 0),
         '$vr21' : RegisterInfo('$xr21', 16, 0),
         '$vr22' : RegisterInfo('$xr22', 16, 0),
         '$vr23' : RegisterInfo('$xr23', 16, 0),
         '$vr24' : RegisterInfo('$xr24', 16, 0),
         '$vr25' : RegisterInfo('$xr25', 16, 0),
         '$vr26' : RegisterInfo('$xr26', 16, 0),
         '$vr27' : RegisterInfo('$xr27', 16, 0),
         '$vr28' : RegisterInfo('$xr28', 16, 0),
         '$vr29' : RegisterInfo('$xr29', 16, 0),
         '$vr30' : RegisterInfo('$xr30', 16, 0),
         '$vr31' : RegisterInfo('$xr31', 16, 0),
         '$fa0' : RegisterInfo('$xr0', 8, 0),
         '$fa1' : RegisterInfo('$xr1', 8, 0),
         '$fa2' : RegisterInfo('$xr2', 8, 0),
         '$fa3' : RegisterInfo('$xr3', 8, 0),
         '$fa4' : RegisterInfo('$xr4', 8, 0),
         '$fa5' : RegisterInfo('$xr5', 8, 0),
         '$fa6' : RegisterInfo('$xr6', 8, 0),
         '$fa7' : RegisterInfo('$xr7', 8, 0),
         '$ft0' : RegisterInfo('$xr8', 8, 0),
         '$ft1' : RegisterInfo('$xr9', 8, 0),
         '$ft2' : RegisterInfo('$xr10', 8, 0),
         '$ft3' : RegisterInfo('$xr11', 8, 0),
         '$ft4' : RegisterInfo('$xr12', 8, 0),
         '$ft5' : RegisterInfo('$xr13', 8, 0),
         '$ft6' : RegisterInfo('$xr14', 8, 0),
         '$ft7' : RegisterInfo('$xr15', 8, 0),
         '$ft8' : RegisterInfo('$xr16', 8, 0),
         '$ft9' : RegisterInfo('$xr17', 8, 0),
         '$ft10' : RegisterInfo('$xr18', 8, 0),
         '$ft11' : RegisterInfo('$xr19', 8, 0),
         '$ft12' : RegisterInfo('$xr20', 8, 0),
         '$ft13' : RegisterInfo('$xr21', 8, 0),
         '$ft14' : RegisterInfo('$xr22', 8, 0),
         '$ft15' : RegisterInfo('$xr23', 8, 0),
         '$fs0' : RegisterInfo('$xr24', 8, 0),
         '$fs1' : RegisterInfo('$xr25', 8, 0),
         '$fs2' : RegisterInfo('$xr26', 8, 0),
         '$fs3' : RegisterInfo('$xr27', 8, 0),
         '$fs4' : RegisterInfo('$xr28', 8, 0),
         '$fs5' : RegisterInfo('$xr29', 8, 0),
         '$fs6' : RegisterInfo('$xr30', 8, 0),
         '$fs7' : RegisterInfo('$xr31', 8, 0),
         '$fcc0' : RegisterInfo('$fcc0', 1, 0),
         '$fcc1' : RegisterInfo('$fcc1', 1, 0),
         '$fcc2' : RegisterInfo('$fcc2', 1, 0),
         '$fcc3' : RegisterInfo('$fcc3', 1, 0),
         '$fcc4' : RegisterInfo('$fcc4', 1, 0),
         '$fcc5' : RegisterInfo('$fcc5', 1, 0),
         '$fcc6' : RegisterInfo('$fcc6', 1, 0),
         '$fcc7' : RegisterInfo('$fcc7', 1, 0),
         '$fcsr0' : RegisterInfo('$fcsr0', 4, 0),
         '$fcsr1' : RegisterInfo('$fcsr1', 4, 0),
         '$fcsr2' : RegisterInfo('$fcsr2', 4, 0),
         '$fcsr3' : RegisterInfo('$fcsr3', 4, 0),
         '$scr0' : RegisterInfo('$scr0', 8 , 0),
         '$scr1' : RegisterInfo('$scr1', 8 , 0),
         '$scr2' : RegisterInfo('$scr2', 8 , 0),
         '$scr3' : RegisterInfo('$scr3', 8 , 0),
         'eflags' : RegisterInfo('eflags', 4, 0),
         'ftop' : RegisterInfo('ftop', 4, 0),
         '$pc' : RegisterInfo('$pc', 8, 0),
    }
    stack_pointer = "$sp"
    link_reg = '$ra'


    def get_instruction_info(self, data, addr):
        if len(data) < 4:
            return None
        result = InstructionInfo()
        result.length = 4
        return result
 
    def get_instruction_text(self, data, addr):
        if len(data) < 4:
            return None
        tokens = [InstructionTextToken(InstructionTextTokenType.TextToken, "HELLO!")]
        return tokens, 4

LoongArch64.register()
